## 1). Import necessary libraries

In [ ]:
import pandas as pd
import numpy as np

## 2). Loading the datasets

In [13]:
df1=pd.read_csv("/workspaces/Exploring_the_Brazi_-Real_Estate_Market_and_Building_a_model_to_predict_property_prices-/data/brasil-real-estate-1.csv")
df2=pd.read_csv("/workspaces/Exploring_the_Brazi_-Real_Estate_Market_and_Building_a_model_to_predict_property_prices-/data/brasil-real-estate-2.csv")

## 3). Cleaning DataSet 1

In [14]:
# Inspection
df1.info()
(df1.isna().sum()/len(df1))*100
duplicates_1=df1.duplicated().sum()
print(f"Total duplicated entries are {duplicates_1}")
df1.head()

<class 'pandas.DataFrame'>
RangeIndex: 12834 entries, 0 to 12833
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               12834 non-null  int64
 1   property_type            12834 non-null  str
 2   place_with_parent_names  12834 non-null  str
 3   region                   12834 non-null  str
 4   lat-lon                  11551 non-null  str
 5   area_m2                  12834 non-null  int64
 6   price_usd                12834 non-null  str
dtypes: int64(2), str(5)
memory usage: 702.0 KB
Total duplicated entries are 0

,Unnamed: 0,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd
0,1,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6443051,-35.7088142",110,"$187,230.85"
1,2,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6430934,-35.70484",65,"$81,133.37"
2,3,house,|Brasil|Alagoas|Maceió|,Northeast,"-9.6227033,-35.7297953",211,"$154,465.45"
3,4,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.622837,-35.719556",99,"$146,013.20"
4,5,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.654955,-35.700227",55,"$101,416.71"

In [15]:
def wrangle_1(df):
    # 1. Drop nulls
    df=df.dropna()

    # 2. Clean "price_usd" column
    df["price_usd"]=(df["price_usd"]
                  .str.replace("$","", regex=False)
                  .str.replace(",", "", regex=False)
                  .astype(float)
                 )
    # 3. Clean "lat-lon"column
    df[["lat", "lon"]]=(df["lat-lon"]
                    .str.split(",", expand=True)
                    .astype(float)
                    )
    # 4. Clean "place_with_parent_name" column
    df["state"]=(df["place_with_parent_names"]
                .str.split("|", expand=True)[2]
                )

    # 5.Drop unnecessary columns
    df.drop(columns=["Unnamed: 0", "place_with_parent_names", "lat-lon"], inplace=True)
   
    return df

In [16]:
df1=wrangle_1(df1)
df1.info()
df1.head()

<class 'pandas.DataFrame'>
Index: 11551 entries, 0 to 12833
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  11551 non-null  str
 1   region         11551 non-null  str
 2   area_m2        11551 non-null  int64
 3   price_usd      11551 non-null  float64
 4   lat            11551 non-null  float64
 5   lon            11551 non-null  float64
 6   state          11551 non-null  str
dtypes: float64(3), int64(1), str(3)
memory usage: 721.9 KB

  property_type     region  area_m2  price_usd       lat        lon    state
0     apartment  Northeast      110  187230.85 -9.644305 -35.708814  Alagoas
1     apartment  Northeast       65   81133.37 -9.643093 -35.704840  Alagoas
2         house  Northeast      211  154465.45 -9.622703 -35.729795  Alagoas
3     apartment  Northeast       99  146013.20 -9.622837 -35.719556  Alagoas
4     apartment  Northeast       55  101416.71 -9.654955 -35.700227  Alagoas

## 4). Cleaning DataSet 2

In [17]:
df2.info()
duplicate_2=df2.duplicated().sum()
print(f"The total number of duplicated entries is {duplicate_2}")
df2.head()

<class 'pandas.DataFrame'>
RangeIndex: 12833 entries, 0 to 12832
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     12833 non-null  int64
 1   property_type  12833 non-null  str
 2   state          12833 non-null  str
 3   region         12833 non-null  str
 4   lat            12833 non-null  float64
 5   lon            12833 non-null  float64
 6   area_m2        11293 non-null  float64
 7   price_brl      12833 non-null  float64
dtypes: float64(4), int64(1), str(3)
memory usage: 802.2 KB
The total number of duplicated entries is 0

,Unnamed: 0,property_type,state,region,lat,lon,area_m2,price_brl
0,1,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72.0,414222.98
1,2,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136.0,848408.53
2,3,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75.0,299438.28
3,4,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187.0,848408.53
4,5,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80.0,464129.36

In [18]:
# Drop nulls
def wrangle_2(df):
    # 1. Drop nulls
    df.dropna(inplace=True)

    # 2. Clean price column
    df["price_usd"]=df["price_brl"]*0.2

    # 3. Modify "area_m2" column
    df2["area_m2"]=df2.area_m2.astype(int)

    # 4. Drop unnecessary columns
    df2.drop(columns=["Unnamed: 0", "price_brl"], inplace=True)
    

    return df

In [19]:
df2=wrangle_2(df2)
df2.info()
df2.head()

<class 'pandas.DataFrame'>
Index: 11293 entries, 0 to 12832
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  11293 non-null  str
 1   state          11293 non-null  str
 2   region         11293 non-null  str
 3   lat            11293 non-null  float64
 4   lon            11293 non-null  float64
 5   area_m2        11293 non-null  int64
 6   price_usd      11293 non-null  float64
dtypes: float64(3), int64(1), str(3)
memory usage: 705.8 KB

,property_type,state,region,lat,lon,area_m2,price_usd
0,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72,82844.596
1,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136,169681.706
2,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75,59887.656
3,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187,169681.706
4,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80,92825.872

## 5). Concatenate the cleaned dataframes into one

In [26]:
df=pd.concat([df2, df1], ignore_index=True)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 22844 entries, 0 to 22843
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  22844 non-null  str
 1   state          22844 non-null  str
 2   region         22844 non-null  str
 3   lat            22844 non-null  float64
 4   lon            22844 non-null  float64
 5   area_m2        22844 non-null  int64
 6   price_usd      22844 non-null  float64
dtypes: float64(3), int64(1), str(3)
memory usage: 1.2 MB

,property_type,state,region,lat,lon,area_m2,price_usd
0,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72,82844.596
1,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136,169681.706
2,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75,59887.656
3,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187,169681.706
4,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80,92825.872

## 6). Save the cleaned csv

In [30]:
df.to_csv("brasil-real-estate-clean.csv", index=False)